const courses = [
  "Accounting",
  "Aerospace Engineering",
  "Architecture",
  "Aviation",
  "Big Data Analytics",
  "Biology",
  "Business Administration",
  "Chemical Engineering",
  "Child Development",
  "Civil Air Transportation Management",
  "Civil Engineering",
  "Clinical Embryology",
  "Computer Engineering",
  "Computer Science",
  "Construction Management",
  "Criminology",
  "Dentistry",
  "Early Childhood Education",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Engineering Management",
  "English Language and Literature",
  "Environmental Engineering",
  "Environmental Science",
  "Finance & Banking",
  "Graphic Design",
  "Geography",
  "Health Education",
  "Healthcare Administration",
  "Healthcare Management",
  "History",
  "Human Resources",
  "Industrial Engineering",
  "Information Technology",
  "Interior Design",
  "International Relations",
  "Journalism",
  "Law",
  "Library Science",
  "Management",
  "Management Information Systems",
  "Maritime Transportation Managament",
  "Marketing",
  "Mathematics",
  "MBA",
  "Mechanical Engineering",
  "Medical Assistant",
  "Medical Biochemistry",
  "Medicine",
  "Molecular Biology & Genetics",
  "Music",
  "Network Administration",
  "Nursing",
  "Nutrition",
  "Occupational Therapy",
  "Paralegal",
  "Pharmacy",
  "Pharmacy Technician",
  "Philosophy",
  "Photography",
  "Physical Therapy",
  "Physics",
  "Political Science",
  "Project Management",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Public Relations",
  "Radiology",
  "Ship Machinery",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Special Education",
  "Sports Management",
  "Statistics",
  "Systems Engineering",
  "Teaching",
  "Tourism & Hotel Mgt",
  "Veterinary Medicine",
  "Veterinary Technician",
  "Zoology",
];

export default courses;
